Python Learnings' -- Numpy Tutorial

NumPy is a core Python library for numerical computing, built for handling large arrays and matrices efficiently.

ndarray object – Stores homogeneous data in n-dimensional arrays for fast processing.
Vectorized operations – Perform element-wise calculations without explicit loops.
Broadcasting – Apply operations across arrays of different shapes.
Linear algebra functions – Matrix multiplication, inversion, eigenvalues, etc.
Statistical tools – Mean, median, standard deviation, and more.
Fourier transforms – Fast computation for signal and image processing.
Integration with other libraries – Works seamlessly with Pandas, SciPy, and scikit-learn.

Important Facts to Know :

NumPy arrays are homogeneous, meaning all elements must be the same type, allowing efficient computation.
Vectorized operations in NumPy can be 10 to 100 times faster than equivalent Python loops.

What is NumPy Used for?
With NumPy, you can perform a wide range of numerical operations, including:

Creating and manipulating arrays.
Performing element-wise and matrix operations.
Generating random numbers and statistical calculations.
Conducting linear algebra operations.
Working with Fourier transformations.
Handling missing values efficiently in datasets.
Why Learn NumPy?
NumPy speeds up math operations like addition and multiplication on large groups of numbers compared to regular Python..
It’s good for handling large lists of numbers (arrays), so you don’t have to write complicated loops.
It gives ready-to-use functions for statistics, algebra and random numbers.
Libraries like Pandas, SciPy, TensorFlow and many others are built on top of NumPy.
NumPy uses less memory and stores data more efficiently, which matters when working with lots of data.
NumPy Basics
This section covers the fundamentals of NumPy, including installation, importing the library and understanding its core functionalities. You will learn about the advantages of NumPy over Python lists and how to set up your environment for efficient numerical computing.

In [2]:
pip install numpy


In [3]:
import numpy as np

In [6]:
# creating a 1 d array
x = np.array([1, 2 , 6])
print(x)
print(type(x))

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])
print(y)

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(z)

[1 2 6]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Using Numpy Functions: NumPy provides convenient methods to create arrays initialized with specific values like zeros and ones:

In [10]:
a = np.zeros((2,2))
print(a)

b = np.ones((2,2))
print(b)

c = np.arange(0, 10, 2)
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


NumPy Array Indexing
Knowing the basics of NumPy array indexing is important for analyzing and manipulating the array object.

Basic Indexing: Basic indexing in NumPy allows you to access elements of an array using indices.

In [17]:
# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr1d[2])

# Negative indexing
print("Negative Indexing :", arr1d[-1])

# creating a multidimensional array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Multidimensional array access
print("Multidimensional array access:" ,arr2[2,2])


Single element access: 30
Negative Indexing : 50
Multidimensional array access: 9


Slicing: Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [21]:

arr = np.array([[1, 2, 3], [4, 5, 6]])
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Range of all rows in second column :",arr [:,1])

Range of Elements: [[4 5 6]]
Range of all rows in second column : [2 5]


NumPy Basic Operations
Element-wise operations in NumPy allow you to perform mathematical operations on each element of an array individually, without the need for explicit loops.

Element-wise Operations: We can perform arithmetic operations like addition, subtraction, multiplication, and division directly on NumPy arrays.

In [22]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y
print("Addition:",add)

# Subtraction
subtract = x - y
print("substration:",subtract)

# Multiplication
multiply = x * y
print("multiplication:",multiply)

# Division
divide = x / y
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


Unary Operation: These operations are applied to each individual element in the array, without the need for multiple arrays (as in binary operations).

In [23]:
# Example array with both positive and negative values
arr = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value
result = np.absolute(arr)
print("Absolute value:", result)

Absolute value: [3 1 0 1 3]


Binary Operators: Numpy Binary Operations apply to the array elementwise and a new array is created. We can use all basic arithmetic operators like +, -, /,  etc. In the case of +=, -=, = operators, the existing array is modified.


In [24]:
 # Two example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Applying a binary operation: addition
result = np.add(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition Result:", result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Addition Result: [5 7 9]


NumPy ufuncs
NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

In [25]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


NumPy Sorting Arrays
We can use a simple np.sort() method for sorting Python NumPy arrays.

In [26]:
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
